### ISSUE TITLE
review of the anatomical BIDS

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/anat#1]
It would be great to have a review of the new BIDS conversion, mainly the filenames.
A few details about the choices:
- to differentiate spine imaging from brain, we use a `bp-cpsine` tag (from BEP025, so not yet BIDS-valid)
- I am nearly completing the script for the defacing of the images, the non-defaced are still versioned but are stored in a different bucket with restricted access.

**Comment by jcohenadad** [comment]
Related discussion (although it doesn't bring much more info): https://github.com/bids-standard/bids-specification/pull/114
